CREATE EXTENSION     IF NOT EXISTS dir_fdw;
CREATE SERVER        IF NOT EXISTS dsv FOREIGN DATA WRAPPER dir_fdw;

CREATE FOREIGN TABLE IF NOT EXISTS dt(
  d_ino    BIGINT,
  d_type   SMALLINT,
  d_name   TEXT
) SERVER dsv OPTIONS(
  dirname '/home'
);

SELECT * FROM dt WHERE d_type=4;

DROP FOREIGN TABLE dt;
DROP SERVER        dsv;
DROP EXTENSION     dir_fdw;
